# Generated by Django 5.2.10 on 2026-01-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
