# Generated by Django 5.2.10 on 2026-01-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
